const express = require("express")
require("dotenv").config()
const path = require("path")
const app = express()
const authRoute = require("./routes/auth_routes")
const postRoute = require("./routes/post_routes")
const subjectRoute = require("./routes/subject_routes")
const lectureRoute = require("./routes/lecture_routes")
const chatRoute = require("./routes/chat_routes")
const userRoute = require("./routes/user_routes")
const periodRoute = require("./routes/period_routes")
const assignmentRoute = require("./routes/assignment_routes")
const attendenceRoute = require("./routes/attendence_routes")
const routineRoute = require("./routes/routine_routes")
const scheduleRoute = require("./routes/schedule_routes")
const cors = require("cors")

app.use(cors())
app.use(express.static(path.join(__dirname, "uploads")))
app.use(express.json())
app.use("/api/v1/auth", authRoute)
app.use("/api/v1/post", postRoute)
app.use("/api/v1/subject", subjectRoute)
app.use("/api/v1/lecture", lectureRoute)
app.use("/api/v1/chat", chatRoute)
app.use("/api/v1/user", userRoute)
app.use("/api/v1/period", periodRoute)
app.use("/api/v1/assignment", assignmentRoute)
app.use("/api/v1/attendence", attendenceRoute)
app.use("/api/v1/routine", routineRoute)
app.use("/api/v1/schedule", scheduleRoute)

app.listen(5000, () => console.log("server listening at port 5000"))
